name: GitHub-Profile-3D-Contrib

on:
  schedule:
    # 매일 새벽 3시 (KST)
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          USERNAME: seungmin-lee-dev

      - name: Commit & Push
        run: |
          git config user.name "seungmin-lee-dev"
          git config user.email "skdhfel8@gmail.com"
          git add -A
          git commit -m "chore: update 3d contribution graph" || exit 0
          git push
